<a href="https://colab.research.google.com/github/smonodeep/DynamicValuationGovernance/blob/main/00.Literature_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The cell below is for reading the content of the Literture Review data.

In [1]:
import requests
import pandas as pd
import io

url='https://raw.githubusercontent.com/smonodeep/DynamicValuationGovernance/main/Literature_Database.csv'

# Fetch the content of the URL
response = requests.get(url)
response.raise_for_status() # Raise an exception for bad status codes

# Split the content into lines
lines = response.text.strip().split('\n')

# The first line is the header, the second is a separator, data starts from the third line
header_line = lines[0]
data_lines = lines[2:]

# Parse the header
# Remove leading/trailing '|', split by '|', and strip whitespace from each column name
headers = [h.strip() for h in header_line.strip('|').split('|')]

# Parse the data
data = []
for line in data_lines:
    # Remove leading/trailing '|', split by '|', and strip whitespace from each value
    row = [v.strip() for v in line.strip('|').split('|')]
    data.append(row)

# Create a DataFrame
df = pd.DataFrame(data, columns=headers)

# Display the head of the DataFrame
display(df)

,S.No,DOI,Publication,Title,Subtitle,Authors,Year,Citation / URL,Exact Abstract,Key Findings,
0,1,**10.1016/S0304-3932(02)00003-1**,Journal of Monetary Economics,The Great Migrations of the 1980s,Case of a Small Open Economy,Assaf Razin & Efraim Sadka,2002,Information Not Available,The paper analyzes the impact of migration on ...,Migration can benefit native-born workers; imp...,
1,2,**10.1111/1540-6229.00555**,Real Estate Economics,Nonparametric Estimation of Dynamic Hedonic Pr...,And the Construction of Residential Housing Pr...,Richard Meese & Nancy Wallace,1991,Information Not Available,This paper explores the use of a nonparametric...,Nonparametric models outperform standard linea...,
2,3,**10.1016/j.jue.2006.10.002**,Journal of Urban Economics,Congestible facility rivalry in vertical struc...,Information Not Available,Leonardo J. Basso & Anming Zhang,2007,Information Not Available,This paper studies the effects of facility riv...,Rivalry generally lowers fees; dominant users ...,
3,4,**10.3386/w14193**,NBER Working Paper,Housing Supply and Housing Bubbles,Information Not Available,"Edward L. Glaeser, Joseph Gyourko & Albert Saiz",2008,Information Not Available,This paper argues that the impact of a housing...,Inelastic supply leads to higher price volatil...,
4,5,**10.3390/agriculture14122211**,Agriculture,Valuation Standards and Estimation Accuracy,In the Appraisal of a Building Housing Vertica...,G. Cucuzza,2024,Information Not Available,Modern agriculture is witnessing a transition ...,Accuracy in ag-tech depends on specialized cap...,
5,6,**10.3390/jrfm15080324**,J. Risk Financial Manag.,Cap Rates as a Function of Real Economic Growth,Information Not Available,M. Larriva,2022,Information Not Available,This paper provides a new framework for unders...,Real economic growth is a primary driver of lo...,
6,7,**10.1051/e3sconf/202338909018**,E3S Web of Conferences,Determination of the capitalization rate,Based on generalization of the trading segment...,"O. Pirogova, V. Plotnikov & N. Tsekhomsky",2023,Information Not Available,This article proposes a method for determining...,Effective price formation depends on standardi...,
7,8,**10.23917/jep.v20i2.6885**,Jurnal Ekonomi Pembangunan,The Capitalization Rate of Real Estate Property,"In Sleman District, Yogyakarta Province, Indon...",P. K. Prasetyanto & H. Sasana,2020,Information Not Available,This study aims to determine the capitalizatio...,Location and property type significantly dicta...,
8,9,**10.3390/buildings12060799**,Buildings,Analytical Implications of Mortgage Lending Va...,Information Not Available,"F. Salvo, M. De Ruggiero, et al.",2022,Information Not Available,This paper explores the analytical implication...,MLV acts as a stabilized value to filter out b...,
9,10,**10.1080/10835547.1993.12090713**,J. Real Estate Research,Estimating Market Values from Appraised Values...,Information Not Available,"Geltner, D.",1993,Information Not Available,This paper presents a simple method for estima...,Appraisals exhibit smoothing and lag effects c...,
10,11,**10.1016/j.frl.2023.104677**,Finance Research Letters,Mortgage lending valuation bias...,Information Not Available,"Reite, E.J.",2023,Information Not Available,We study the impact of loan-to-value (LTV) reg...,LTV regulations can incentivize appraisers to ...,
11,12,Info Not Available,Bank for Int. Settlements,Guidelines on credit risk and accounting for ECL,Information Not Available,BCBS,2017,Link,Information Not Available,AVM outputs influence LTV and ECL; governance ...,
12,13,Info Not Available,Federal Reserve / OCC,Supervisory guidance on model risk management ...,Information Not Available,Fed/OCC,2011,Link,Information Not Available,Establishes institution-wide standards for mod...,
13,14,Info Not Available,BIS Working Paper,Towards a macroprudential framework...,Information Not Available,"Borio, C.",2003,Link,Information Not Available,AVMs may stabilize lending metrics while maski...,
14,15,Info Not Available,BIS Papers No. 1,Pro-cyclicality of the financial system...,Issues and policy options,"Borio, C. et al.",2001,Link,Information Not Available,Collateral valuations play a role in amplifyin...,
15,16,**10.1108/14635780010324240**,Journal of Property Research,"Valuation accuracy, variation and bias...",In the context of standards and expectations,"Crosby, N.",2000,Information Not Available,Information Not Available,AVM accuracy and bias are critical in the cont...,
16,17,Info Not Available,European Banking Authority,Guidelines on credit risk management practices...,Information Not Available,EBA,2017,Link,Information Not Available,Governance and judgmental overlays are central...,
17,18,**10.1108/14635780410569470**,J. Prop. Inv. & Finance,Uncertainty in valuation: A framework for anal...,Information Not Available,"French, N. & Gabrielli, L.",2018,Information Not Available,Information Not Available,Structural variations in market evidence gener...,
18,19,Info Not Available,Cengage Learning (Book),Commercial Real Estate Analysis and Investments,3rd Edition,"Geltner, D. et al.",2014,Information Not Available,Information Not Available,Model-based valuations exhibit smoothing and l...,
19,20,Info Not Available,IFRS Foundation,IFRS 9 Financial Instruments,Information Not Available,IASB,2014,Link,Information Not Available,Collateral values are a key input for Expected...,
20,21,Info Not Available,IVSC Manual,International Valuation Standards,Information Not Available,IVSC,2020,Link,Information Not Available,Standards acknowledge uncertainty and the nece...,None

In [2]:
import pandas as pd

# Set display options to show all columns and prevent truncation
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# Display the DataFrame again with updated settings
display(df)

,S.No,DOI,Publication,Title,Subtitle,Authors,Year,Citation / URL,Exact Abstract,Key Findings,
0,1,**10.1016/S0304-3932(02)00003-1**,Journal of Monetary Economics,The Great Migrations of the 1980s,Case of a Small Open Economy,Assaf Razin & Efraim Sadka,2002,Information Not Available,The paper analyzes the impact of migration on ...,Migration can benefit native-born workers; imp...,
1,2,**10.1111/1540-6229.00555**,Real Estate Economics,Nonparametric Estimation of Dynamic Hedonic Pr...,And the Construction of Residential Housing Pr...,Richard Meese & Nancy Wallace,1991,Information Not Available,This paper explores the use of a nonparametric...,Nonparametric models outperform standard linea...,
2,3,**10.1016/j.jue.2006.10.002**,Journal of Urban Economics,Congestible facility rivalry in vertical struc...,Information Not Available,Leonardo J. Basso & Anming Zhang,2007,Information Not Available,This paper studies the effects of facility riv...,Rivalry generally lowers fees; dominant users ...,
3,4,**10.3386/w14193**,NBER Working Paper,Housing Supply and Housing Bubbles,Information Not Available,"Edward L. Glaeser, Joseph Gyourko & Albert Saiz",2008,Information Not Available,This paper argues that the impact of a housing...,Inelastic supply leads to higher price volatil...,
4,5,**10.3390/agriculture14122211**,Agriculture,Valuation Standards and Estimation Accuracy,In the Appraisal of a Building Housing Vertica...,G. Cucuzza,2024,Information Not Available,Modern agriculture is witnessing a transition ...,Accuracy in ag-tech depends on specialized cap...,
5,6,**10.3390/jrfm15080324**,J. Risk Financial Manag.,Cap Rates as a Function of Real Economic Growth,Information Not Available,M. Larriva,2022,Information Not Available,This paper provides a new framework for unders...,Real economic growth is a primary driver of lo...,
6,7,**10.1051/e3sconf/202338909018**,E3S Web of Conferences,Determination of the capitalization rate,Based on generalization of the trading segment...,"O. Pirogova, V. Plotnikov & N. Tsekhomsky",2023,Information Not Available,This article proposes a method for determining...,Effective price formation depends on standardi...,
7,8,**10.23917/jep.v20i2.6885**,Jurnal Ekonomi Pembangunan,The Capitalization Rate of Real Estate Property,"In Sleman District, Yogyakarta Province, Indon...",P. K. Prasetyanto & H. Sasana,2020,Information Not Available,This study aims to determine the capitalizatio...,Location and property type significantly dicta...,
8,9,**10.3390/buildings12060799**,Buildings,Analytical Implications of Mortgage Lending Va...,Information Not Available,"F. Salvo, M. De Ruggiero, et al.",2022,Information Not Available,This paper explores the analytical implication...,MLV acts as a stabilized value to filter out b...,
9,10,**10.1080/10835547.1993.12090713**,J. Real Estate Research,Estimating Market Values from Appraised Values...,Information Not Available,"Geltner, D.",1993,Information Not Available,This paper presents a simple method for estima...,Appraisals exhibit smoothing and lag effects c...,
10,11,**10.1016/j.frl.2023.104677**,Finance Research Letters,Mortgage lending valuation bias...,Information Not Available,"Reite, E.J.",2023,Information Not Available,We study the impact of loan-to-value (LTV) reg...,LTV regulations can incentivize appraisers to ...,
11,12,Info Not Available,Bank for Int. Settlements,Guidelines on credit risk and accounting for ECL,Information Not Available,BCBS,2017,Link,Information Not Available,AVM outputs influence LTV and ECL; governance ...,
12,13,Info Not Available,Federal Reserve / OCC,Supervisory guidance on model risk management ...,Information Not Available,Fed/OCC,2011,Link,Information Not Available,Establishes institution-wide standards for mod...,
13,14,Info Not Available,BIS Working Paper,Towards a macroprudential framework...,Information Not Available,"Borio, C.",2003,Link,Information Not Available,AVMs may stabilize lending metrics while maski...,
14,15,Info Not Available,BIS Papers No. 1,Pro-cyclicality of the financial system...,Issues and policy options,"Borio, C. et al.",2001,Link,Information Not Available,Collateral valuations play a role in amplifyin...,
15,16,**10.1108/14635780010324240**,Journal of Property Research,"Valuation accuracy, variation and bias...",In the context of standards and expectations,"Crosby, N.",2000,Information Not Available,Information Not Available,AVM accuracy and bias are critical in the cont...,
16,17,Info Not Available,European Banking Authority,Guidelines on credit risk management practices...,Information Not Available,EBA,2017,Link,Information Not Available,Governance and judgmental overlays are central...,
17,18,**10.1108/14635780410569470**,J. Prop. Inv. & Finance,Uncertainty in valuation: A framework for anal...,Information Not Available,"French, N. & Gabrielli, L.",2018,Information Not Available,Information Not Available,Structural variations in market evidence gener...,
18,19,Info Not Available,Cengage Learning (Book),Commercial Real Estate Analysis and Investments,3rd Edition,"Geltner, D. et al.",2014,Information Not Available,Information Not Available,Model-based valuations exhibit smoothing and l...,
19,20,Info Not Available,IFRS Foundation,IFRS 9 Financial Instruments,Information Not Available,IASB,2014,Link,Information Not Available,Collateral values are a key input for Expected...,
20,21,Info Not Available,IVSC Manual,International Valuation Standards,Information Not Available,IVSC,2020,Link,Information Not Available,Standards acknowledge uncertainty and the nece...,None

In [3]:
doi_links = df['DOI'].dropna().unique()
url_links = df['Citation / URL'].dropna().unique()

# Count the number of actual links, excluding 'Info Not Available' or 'Link' placeholders
doi_link_count = sum(1 for link in doi_links if link not in ['Info Not Available', 'Link', '**Info Not Available**'])
url_link_count = sum(1 for link in url_links if link not in ['Info Not Available', 'Link', '**Info Not Available**'])

total_links = doi_link_count + url_link_count

print(f"Number of unique DOI links: {doi_link_count}")
print(f"Number of unique Citation / URL links: {url_link_count}")
print(f"Total unique links (from DOI and Citation / URL columns): {total_links}")

Number of unique DOI links: 13
Number of unique Citation / URL links: 1
Total unique links (from DOI and Citation / URL columns): 14

### Creating Working Links from DOI

To make the DOIs clickable, I will extract the DOI identifier from the 'DOI' column and prepend `https://doi.org/` to it, creating a new column `DOI_Link`. This will allow direct access to the publication by clicking the link.

In [12]:
def create_doi_link(doi_string):
    if isinstance(doi_string, str) and '**' in doi_string:
        # Remove the '**' at the beginning and end
        cleaned_doi = doi_string.strip('**')
        return f"https://doi.org/{cleaned_doi}"
    return None # Return None for non-string or invalid DOI entries

# Apply the function to the 'DOI' column to create the new 'DOI_Link' column
df['DOI_Link'] = df['DOI'].apply(create_doi_link)

# Display the DataFrame with the new 'DOI_Link' column
display(df[['S.No', 'DOI', 'Publication', 'Title','Authors','Year','Exact Abstract']])

,S.No,DOI,Publication,Title,Authors,Year,Exact Abstract
0,1,**10.1016/S0304-3932(02)00003-1**,Journal of Monetary Economics,The Great Migrations of the 1980s,Assaf Razin & Efraim Sadka,2002,The paper analyzes the impact of migration on ...
1,2,**10.1111/1540-6229.00555**,Real Estate Economics,Nonparametric Estimation of Dynamic Hedonic Pr...,Richard Meese & Nancy Wallace,1991,This paper explores the use of a nonparametric...
2,3,**10.1016/j.jue.2006.10.002**,Journal of Urban Economics,Congestible facility rivalry in vertical struc...,Leonardo J. Basso & Anming Zhang,2007,This paper studies the effects of facility riv...
3,4,**10.3386/w14193**,NBER Working Paper,Housing Supply and Housing Bubbles,"Edward L. Glaeser, Joseph Gyourko & Albert Saiz",2008,This paper argues that the impact of a housing...
4,5,**10.3390/agriculture14122211**,Agriculture,Valuation Standards and Estimation Accuracy,G. Cucuzza,2024,Modern agriculture is witnessing a transition ...
5,6,**10.3390/jrfm15080324**,J. Risk Financial Manag.,Cap Rates as a Function of Real Economic Growth,M. Larriva,2022,This paper provides a new framework for unders...
6,7,**10.1051/e3sconf/202338909018**,E3S Web of Conferences,Determination of the capitalization rate,"O. Pirogova, V. Plotnikov & N. Tsekhomsky",2023,This article proposes a method for determining...
7,8,**10.23917/jep.v20i2.6885**,Jurnal Ekonomi Pembangunan,The Capitalization Rate of Real Estate Property,P. K. Prasetyanto & H. Sasana,2020,This study aims to determine the capitalizatio...
8,9,**10.3390/buildings12060799**,Buildings,Analytical Implications of Mortgage Lending Va...,"F. Salvo, M. De Ruggiero, et al.",2022,This paper explores the analytical implication...
9,10,**10.1080/10835547.1993.12090713**,J. Real Estate Research,Estimating Market Values from Appraised Values...,"Geltner, D.",1993,This paper presents a simple method for estima...
10,11,**10.1016/j.frl.2023.104677**,Finance Research Letters,Mortgage lending valuation bias...,"Reite, E.J.",2023,We study the impact of loan-to-value (LTV) reg...
11,12,Info Not Available,Bank for Int. Settlements,Guidelines on credit risk and accounting for ECL,BCBS,2017,Information Not Available
12,13,Info Not Available,Federal Reserve / OCC,Supervisory guidance on model risk management ...,Fed/OCC,2011,Information Not Available
13,14,Info Not Available,BIS Working Paper,Towards a macroprudential framework...,"Borio, C.",2003,Information Not Available
14,15,Info Not Available,BIS Papers No. 1,Pro-cyclicality of the financial system...,"Borio, C. et al.",2001,Information Not Available
15,16,**10.1108/14635780010324240**,Journal of Property Research,"Valuation accuracy, variation and bias...","Crosby, N.",2000,Information Not Available
16,17,Info Not Available,European Banking Authority,Guidelines on credit risk management practices...,EBA,2017,Information Not Available
17,18,**10.1108/14635780410569470**,J. Prop. Inv. & Finance,Uncertainty in valuation: A framework for anal...,"French, N. & Gabrielli, L.",2018,Information Not Available
18,19,Info Not Available,Cengage Learning (Book),Commercial Real Estate Analysis and Investments,"Geltner, D. et al.",2014,Information Not Available
19,20,Info Not Available,IFRS Foundation,IFRS 9 Financial Instruments,IASB,2014,Information Not Available
20,21,Info Not Available,IVSC Manual,International Valuation Standards,IVSC,2020,Information Not Available

In [7]:
df.columns.to_list()

['S.No',
 'DOI',
 'Publication',
 'Title',
 'Subtitle',
 'Authors',
 'Year',
 'Citation / URL',
 'Exact Abstract',
 'Key Findings',
 '',
 'DOI_Link']