In [1]:
!pip install -q mospi-esankhyiki

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.2/74.2 kB 995.2 kB/s eta 0:00:00

In [2]:
import pandas as pd
import numpy as np
import esankhyiki

from esankhyiki.exceptions import (
    InvalidDatasetError,
    InvalidFilterError,
    APIError,
    NoDataError
)

In [3]:
datasets = esankhyiki.list_datasets(format="df")
display(datasets)

     dataset
0       PLFS
1        CPI
2        IIP
3        ASI
4        NAS
5        WPI
6     ENERGY
7      AISHE
8      ASUSE
9     GENDER
10      NFHS
11  ENVSTATS
12       RBI
13     NSS77
14     NSS78
15   CPIALRL
16      HCES
17       TUS
18        EC
19     NSS73
20     NSS75
21    NSS75E
22     NSS76
23    NSS76C
24     NSS79
25     NSS80
26    NSS80C
27     UDISE
28      MNRE
29       ISP

In [4]:
datasets.to_csv(
    "mospi_esankhyiki_dataset_catalogue.csv",
    index=False
)

In [5]:
plfs_indicators = esankhyiki.get_indicators("PLFS")

for frequency, items in plfs_indicators["indicators_by_frequency"].items():
    print(f"\n===== {frequency} =====")
    for item in items:
        print(
            item.get("indicator_code"),
            "|",
            item.get("indicator_name", item.get("description", ""))
        )

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

===== frequency_code_1_Annual =====
1 | LFPR (Labour Force Participation Rate, in per cent)
2 | WPR (Worker Population Ratio, in per cent)
3 | UR (Unemployment Rate, in per cent)
4 | Percentage distribution of workers
5 | Percentage of regular wage/ salaried employees with employment condition as
6 | Average wage/salary earnings (Rs. 0.00) during the preceding calendar month from regular wage/salaried employment
7 | Average wage earnings (Rs. 0.00) per day from casual labour work other than public works
8 | Average gross earnings (Rs. 0.00) during last 30 days from self-employment

===== frequency_code_2_Quarterly =====
1 | LFPR (Labour Force Participation Rate, in per cent)
2 | WPR (Worker Population Ratio, in per cent)
3 | UR (Unemployment Rate, in per cent)
4 | Percentage distribution of workers

===== frequency_code_3_Monthly =====
1 | LFPR (Labour Force Participation Rate, in per cent)
2 | WPR (Worker Population Ratio, in per cent)
3 | UR (Unemployment Rate, in per cent)

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [6]:
metadata = esankhyiki.get_metadata(
    "PLFS",
    indicator_code=3,
    frequency_code=1,
    year_type_code=1
)

for key, values in metadata["filter_values"]["data"].items():
    print("\n", key)
    for value in values[:20]:
        print(value)

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

 year_type
{'description': 'Calendar Year', 'year_type_code': 2}
{'description': 'Agriculture Year', 'year_type_code': 1}

 year
{'year': '2025'}
{'year': '2024'}
{'year': '2023-24'}
{'year': '2023'}
{'year': '2022-23'}
{'year': '2022'}
{'year': '2021-22'}
{'year': '2020-21'}
{'year': '2019-20'}
{'year': '2018-19'}
{'year': '2017-18'}

 age
{'age_code': 1, 'description': '15 years and above'}
{'age_code': 2, 'description': '15-29 years'}
{'age_code': 3, 'description': '15-59 years'}
{'age_code': 4, 'description': 'All ages'}

 education
{'description': 'all', 'education_code': 0}
{'description': '1.not literate', 'education_code': 1}
{'description': '2.literate & upto primary', 'education_code': 2}
{'description': '3.middle', 'education_code': 3}
{'description': '4.secondary', 'education_code': 4}
{'description': '5.higher secondary', 'education_code': 5}
{'description': '6.diploma/ certificate course', 'education_code': 6}
{'description': '7.graduate', 'education_code': 7}
{'description': '8.post graduate & above', 'education_code': 8}
{'description': '9.secondary & above', 'education_code': 9}

 gender
{'description': 'male', 'gender_code': 1}
{'description': 'female', 'gender_code': 2}
{'description': 'person', 'gender_code': 3}

 religion
{'description': 'all', 'religion_code': 1}
{'description': 'Hinduism', 'religion_code': 2}
{'description': 'Islam', 'religion_code': 3}
{'description': 'Christianity', 'religion_code': 4}
{'description': 'Sikhism', 'religion_code': 5}

 sector
{'description': 'rural', 'sector_code': 1}
{'description': 'urban', 'sector_code': 2}
{'description': 'rural + urban', 'sector_code': 3}

 social_category
{'description': 'all', 'social_category_code': 1}
{'description': 'scheduled tribe', 'social_category_code': 2}
{'description': 'scheduled caste', 'social_category_code': 3}
{'description': 'other backward class', 'social_category_code': 4}
{'description': 'others', 'social_category_code': 5}

 state
{'state_code': 99, 'description': 'All India'}
{'state_code': 31, 'description': 'Andaman & Nicobar Islands'}
{'state_code': 1, 'description': 'Andhra Pradesh'}
{'state_code': 2, 'description': 'Arunachal Pradesh'}
{'state_code': 3, 'description': 'Assam'}
{'state_code': 4, 'description': 'Bihar'}
{'state_code': 32, 'description': 'Chandigarh'}
{'state_code': 5, 'description': 'Chhattisgarh'}
{'state_code': 33, 'description': 'Dadra & Nagar Haveli'}
{'state_code': 38, 'description': 'Dadra & Nagar Haveli & Daman & Diu'}
{'state_code': 34, 'description': 'Daman & Diu'}
{'state_code': 6, 'description': 'Delhi'}
{'state_code': 7, 'description': 'Goa'}
{'state_code': 8, 'description': 'Gujarat'}
{'state_code': 9, 'description': 'Haryana'}
{'state_code': 10, 'description': 'Himachal Pradesh'}
{'state_code': 11, 'description': 'Jammu & Kashmir'}
{'state_code': 12, 'description': 'Jharkhand'}
{'state_code': 13, 'description': 'Karnataka'}
{'state_code': 14, 'description': 'Kerala'}

 weekly_status
{'description': 'PS+SS', 'weekly_status_code': 1}
{'description': 'CWS', 'weekly_status_code': 2}

In [52]:
plfs = esankhyiki.get_data(
    "PLFS",
    {
        "indicator_code": 3,
        "frequency_code": 1,
        "year_type_code": 1,
        "state_code": 99,
        "gender_code": 3,
        "age_code": 1,
        "sector_code": 3,
    },
    format="df"
)

display(plfs.head(2))
display(plfs.shape)

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&state_code=99&gender_code=3&age_code=1&sector_code=3&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"6.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"scheduled tribe","General_Education":"all","quarter":"all","month":null,"value":"4.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"scheduled caste","General_Education":"all","quarter":"all","month":null,"value":"6.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"other backward class","General_Education":"all","quarter":"all","month":null,"value":"5.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"others","General_Education":"all","quarter":"all","month":null,"value":"6.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"Hinduism","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"5.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"Islam","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"Christianity","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"Sikhism","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"6.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"5.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"10.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"19.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"17.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"14.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"11.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"scheduled tribe","General_Education":"all","quarter":"all","month":null,"value":"4.3","unit":"%"}],"meta_data":{"page":1,"totalRecords":133,"totalPages":7,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================

,year_type,year,frequency,indicator,state,gender,sector,AgeGroup,weekly_status,religion,socialGroup,General_Education,quarter,month,value,unit
0,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,all,all,all,None,6.0,%
1,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,scheduled tribe,all,all,None,4.2,%

(20, 16)

Create a Master UR table

In [54]:
import pandas as pd
import esankhyiki

# Common PLFS parameters
base_params = {
    "indicator_code": 3,
    "frequency_code": 1,
    "year_type_code": 1,
    "gender_code": 3,
    "age_code": 1,
    "sector_code": 3,
}

all_plfs = []

# ---------------------------------------------------------
# 1. Extract state-level data: state_code 1 to 38
# ---------------------------------------------------------

for state_code in range(1, 39):

    print(f"Extracting state_code = {state_code}")

    params = {
        **base_params,
        "state_code": state_code
    }

    df_state = esankhyiki.get_data(
        "PLFS",
        params,
        format="df"
    )

    # Keep the source state identifier explicitly
    df_state["state_code"] = state_code

    all_plfs.append(df_state)


# ---------------------------------------------------------
# 2. Extract national-level data: state_code = 99
# ---------------------------------------------------------

print("Extracting national-level data: state_code = 99")

params_national = {
    **base_params,
    "state_code": 99
}

df_national = esankhyiki.get_data(
    "PLFS",
    params_national,
    format="df"
)

df_national["state_code"] = 99

all_plfs.append(df_national)


# ---------------------------------------------------------
# 3. Concatenate everything
# ---------------------------------------------------------

plfs_master = pd.concat(
    all_plfs,
    ignore_index=True
)

print("Master shape:", plfs_master.shape)
print(plfs_master.head())
print(plfs_master.tail())
plfs_master.to_csv('UR.csv', index=False)

Extracting state_code = 1
================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=1&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"4.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"1.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"3.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"8.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"28.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"25.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"23.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"14.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"1.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"3.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"9.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"27.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"27.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"22.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andhra Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"15.2","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 2

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=2&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"5.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"6.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"2.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"3.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"6.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"10.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"20.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"14.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"12.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"2.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"4.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"3.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"6.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"11.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"28.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"54.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Arunachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"15.8","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 3
================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=3&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"3.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"9.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"8.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"19.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"28.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"13.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"17.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"13.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"4.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"3.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"8.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"13.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"8.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"16.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"9.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Assam","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"12.2","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 4

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=4&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"3.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"5.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"9.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"9.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"42.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"15.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"17.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"10.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"3.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"9.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"13.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"11.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"11.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"7.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"23.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"4.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Bihar","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"14.5","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 5
================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=5&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"3.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"4.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"2.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"5.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"19.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"17.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"18.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"8.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"3.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"2.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"3.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"12.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"7.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"10.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chhattisgarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"5.0","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 6

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=6&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"9.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"10.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"2.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"3.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"10.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"11.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"14.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"10.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"13.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"6.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"12.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"5.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"13.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"10.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"6.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"8.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"15.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"11.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Delhi","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"10.8","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 7
================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=7&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"13.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"15.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"6.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"15.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"11.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"15.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"9.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"18.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"24.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"15.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"5.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"13.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"12.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"6.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"13.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"17.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Goa","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"12.8","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 8

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=8&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"4.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"5.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"5.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"4.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"6.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"22.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"8.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"10.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"7.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"3.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"4.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"3.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"5.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"7.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"8.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Gujarat","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"5.4","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 9
================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=9&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"11.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"2.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"5.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"8.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"6.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"12.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"21.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"17.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"8.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"11.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"2.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"3.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"10.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"8.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"11.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"21.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"16.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"12.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Haryana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"12.9","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 10

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=10&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"5.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"1.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"1.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"10.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"11.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"22.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"30.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"9.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"1.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"2.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"9.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"9.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"19.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"21.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Himachal Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"9.2","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 11

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=11&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"5.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"9.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"2.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"4.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"10.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"13.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"20.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"18.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"11.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"1.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"1.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"7.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"11.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"17.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"28.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jammu & Kashmir","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"11.8","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 12

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=12&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"11.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"4.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"8.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"8.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"14.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"40.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"20.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"13.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"13.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"4.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"5.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"11.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"15.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"14.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"9.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Jharkhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"9.6","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 13

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=13&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"4.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"6.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"4.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"4.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"7.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"22.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"12.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"14.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"9.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"3.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"4.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"9.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"9.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"10.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Karnataka","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"7.0","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 14

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=14&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"11.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"14.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"2.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"7.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"22.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"21.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"30.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"24.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"19.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"1.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"6.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"17.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"18.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"25.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"22.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Kerala","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"16.2","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 15

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=15&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"4.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"8.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"9.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"12.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"9.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"8.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"2.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"4.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"12.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"11.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"9.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Madhya Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"6.8","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 16

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=16&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"4.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"3.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"8.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"10.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"10.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"8.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"8.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"4.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"3.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"9.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"8.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"12.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"7.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Maharashtra","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"8.2","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 17

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=17&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"11.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"11.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"6.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"9.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"14.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"11.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"26.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"21.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"17.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"4.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"6.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"11.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"17.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"20.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Manipur","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"13.1","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 18

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=18&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"1.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"1.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"0.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"1.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"3.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"12.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"8.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"5.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"1.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"6.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"14.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"14.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"8.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Meghalaya","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"8.8","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 19

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=19&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"10.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"10.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"9.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"9.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"18.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"20.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"19.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"16.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"8.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"11.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"11.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"12.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Mizoram","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"10.5","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 20

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=20&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"21.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"22.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"3.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"19.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"17.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"28.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"8.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"45.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"35.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"30.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"11.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"14.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"36.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"30.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"23.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Nagaland","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"26.6","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 21

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=21&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"10.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"8.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"11.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"17.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"35.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"19.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"17.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"16.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"7.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"13.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"14.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"25.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"20.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"7.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Odisha","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"16.0","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 22

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=22&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"9.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"2.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"4.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"12.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"20.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"13.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"18.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"11.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"3.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"7.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"3.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"14.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"17.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"17.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"16.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Punjab","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"11.2","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 23

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=23&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"5.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"9.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"5.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"4.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"9.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"26.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"17.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"15.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"11.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"3.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"3.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"9.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"26.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"21.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"23.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Rajasthan","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"13.7","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 24

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=24&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"3.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"4.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"0.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"1.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"8.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"15.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"14.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"8.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"1.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"8.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"3.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"8.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"8.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Sikkim","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"6.5","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 25

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=25&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"11.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"4.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"6.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"10.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"18.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"25.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"13.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"15.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"2.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"4.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"8.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"22.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"21.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"15.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tamil Nadu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"14.0","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 26

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=26&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"4.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"4.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"12.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"13.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"27.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"22.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"15.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"4.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"10.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"34.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"27.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"31.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Telangana","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"16.7","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 27

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=27&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"6.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"3.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"11.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"9.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"37.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"12.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"18.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"12.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"13.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"15.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"16.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"56.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"20.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"15.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Tripura","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"17.2","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 28

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=28&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"2.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"2.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"6.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"6.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"18.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"21.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"26.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"12.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"2.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"4.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"4.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"8.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"18.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"21.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"23.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttarakhand","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"13.6","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 29

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=29&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"6.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"9.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"5.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"5.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"9.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"14.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"16.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"12.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"10.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"3.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"5.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"8.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"34.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"16.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"9.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Uttar Pradesh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"10.3","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 30

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=30&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"4.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"6.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"8.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"29.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"12.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"13.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"9.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"2.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"10.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"12.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"10.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"8.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"West Bengal","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"9.0","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 31

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=31&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"15.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"16.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"8.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"15.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"37.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"25.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"25.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"30.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"26.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"1.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"7.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"15.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"34.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"25.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"40.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Andaman & Nicobar Islands","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"24.7","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 32

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=32&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"9.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"9.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"4.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"6.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"11.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"19.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"14.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"12.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"2.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"3.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"4.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"1.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"16.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"14.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"4.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Chandigarh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"8.5","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 33

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=33&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"0.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"3.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"0.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"4.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"0.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"3.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"5.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"4.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"3.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"4.0","unit":"%"}],"meta_data":{"page":1,"totalRecords":33,"totalPages":2,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 34

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=34&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"3.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"3.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"0.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"0.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"6.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"4.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"17.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"6.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"0.1","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"0.1","unit":"%"}],"meta_data":{"page":1,"totalRecords":33,"totalPages":2,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 35
================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=35&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"21.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"22.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"18.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"24.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"30.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"15.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"55.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"6.1","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"26.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"8.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"13.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"28.6","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"55.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"72.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"39.7","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"12.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Lakshadweep","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"42.0","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 36

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=36&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"10.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"12.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"3.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"1.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"4.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"3.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"11.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"20.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"28.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"14.0","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"5.9","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"4.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"4.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"3.8","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"5.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"10.5","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"22.3","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"7.2","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Puducherry","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"11.4","unit":"%"}],"meta_data":{"page":1,"totalRecords":77,"totalPages":4,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 37
================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=37&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2019-20","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"0.1","unit":"%"},{"year_type":"Agriculture Year","year":"2019-20","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"5.3","unit":"%"},{"year_type":"Agriculture Year","year":"2019-20","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2019-20","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2019-20","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2019-20","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2019-20","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"1.2","unit":"%"},{"year_type":"Agriculture Year","year":"2019-20","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2019-20","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2019-20","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2019-20","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"0.3","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"2.9","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"9.0","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"3.8","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Ladakh","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"10.7","unit":"%"}],"meta_data":{"page":1,"totalRecords":55,"totalPages":3,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting state_code = 38

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=38&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"4.2","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"4.8","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"11.4","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.2","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"4.5","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"3.6","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"1.7","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"7.4","unit":"%"},{"year_type":"Agriculture Year","year":"2020-21","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"3.8","unit":"%"},{"year_type":"Agriculture Year","year":"2021-22","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"5.2","unit":"%"},{"year_type":"Agriculture Year","year":"2021-22","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"6.2","unit":"%"},{"year_type":"Agriculture Year","year":"2021-22","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"6.2","unit":"%"},{"year_type":"Agriculture Year","year":"2021-22","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"0.0","unit":"%"},{"year_type":"Agriculture Year","year":"2021-22","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"6.1","unit":"%"},{"year_type":"Agriculture Year","year":"2021-22","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.3","unit":"%"},{"year_type":"Agriculture Year","year":"2021-22","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"6.9","unit":"%"},{"year_type":"Agriculture Year","year":"2021-22","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"18.7","unit":"%"},{"year_type":"Agriculture Year","year":"2021-22","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"Dadra & Nagar Haveli & Daman & Diu","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"3.6","unit":"%"}],"meta_data":{"page":1,"totalRecords":44,"totalPages":3,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Extracting national-level data: state_code = 99
================================================================================
URL: https://api.mospi.gov.in/api/plfs/getData?indicator_code=3&frequency_code=1&year_type_code=1&gender_code=3&age_code=1&sector_code=3&state_code=99&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"6.0","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"scheduled tribe","General_Education":"all","quarter":"all","month":null,"value":"4.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"scheduled caste","General_Education":"all","quarter":"all","month":null,"value":"6.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"other backward class","General_Education":"all","quarter":"all","month":null,"value":"5.9","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"others","General_Education":"all","quarter":"all","month":null,"value":"6.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"Hinduism","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"5.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"Islam","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"7.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"Christianity","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.4","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"Sikhism","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"6.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"CWS","religion":"all","socialGroup":"all","General_Education":"all","quarter":"all","month":null,"value":"8.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"1.not literate","quarter":"all","month":null,"value":"1.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"2.literate & upto primary","quarter":"all","month":null,"value":"2.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"3.middle","quarter":"all","month":null,"value":"5.5","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"4.secondary","quarter":"all","month":null,"value":"5.7","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"5.higher secondary","quarter":"all","month":null,"value":"10.3","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"6.diploma/ certificate course","quarter":"all","month":null,"value":"19.8","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"7.graduate","quarter":"all","month":null,"value":"17.2","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"8.post graduate & above","quarter":"all","month":null,"value":"14.6","unit":"%"},{"year_type":"Agriculture Year","year":"2017-18","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"all","General_Education":"9.secondary & above","quarter":"all","month":null,"value":"11.4","unit":"%"},{"year_type":"Agriculture Year","year":"2018-19","frequency":"Annually","indicator":"UR (Unemployment Rate, in per cent)","state":"All India","gender":"person","sector":"rural + urban","AgeGroup":"15 years and above","weekly_status":"PS+SS","religion":"all","socialGroup":"scheduled tribe","General_Education":"all","quarter":"all","month":null,"value":"4.3","unit":"%"}],"meta_data":{"page":1,"totalRecords":133,"totalPages":7,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================
Master shape: (780, 17)
          year_type     year frequency                            indicator  \
0  Agriculture Year  2017-18  Annually  UR (Unemployment Rate, in per cent)
1  Agriculture Year  2017-18  Annually  UR (Unemployment Rate, in per cent)
2  Agriculture Year  2017-18  Annually  UR (Unemployment Rate, in per cent)
3  Agriculture Year  2017-18  Annually  UR (Unemployment Rate, in per cent)
4  Agriculture Year  2017-18  Annually  UR (Unemployment Rate, in per cent)

            state  gender         sector            AgeGroup weekly_status  \
0  Andhra Pradesh  person  rural + urban  15 years and above         PS+SS
1  Andhra Pradesh  person  rural + urban  15 years and above           CWS
2  Andhra Pradesh  person  rural + urban  15 years and above         PS+SS
3  Andhra Pradesh  person  rural + urban  15 years and above         PS+SS
4  Andhra Pradesh  person  rural + urban  15 years and above         PS+SS

  religion socialGroup          General_Education quarter month value unit  \
0      all         all                        all     all  None   4.5    %
1      all         all                        all     all  None   8.4    %
2      all         all             1.not literate     all  None   0.1    %
3      all         all  2.literate & upto primary     all  None   0.5    %
4      all         all                   3.middle     all  None   1.5    %

   state_code
0           1
1           1
2           1
3           1
4           1
            year_type     year frequency                            indicator  \
775  Agriculture Year  2017-18  Annually  UR (Unemployment Rate, in per cent)
776  Agriculture Year  2017-18  Annually  UR (Unemployment Rate, in per cent)
777  Agriculture Year  2017-18  Annually  UR (Unemployment Rate, in per cent)
778  Agriculture Year  2017-18  Annually  UR (Unemployment Rate, in per cent)
779  Agriculture Year  2018-19  Annually  UR (Unemployment Rate, in per cent)

         state  gender         sector            AgeGroup weekly_status  \
775  All India  person  rural + urban  15 years and above         PS+SS
776  All India  person  rural + urban  15 years and above         PS+SS
777  All India  person  rural + urban  15 years and above         PS+SS
778  All India  person  rural + urban  15 years and above         PS+SS
779  All India  person  rural + urban  15 years and above         PS+SS

    religion      socialGroup              General_Education quarter month  \
775      all              all  6.diploma/ certificate course     all  None
776      all              all                     7.graduate     all  None
777      all              all        8.post graduate & above     all  None
778      all              all            9.secondary & above     all  None
779      all  scheduled tribe                            all     all  None

    value unit  state_code
775  19.8    %          99
776  17.2    %          99
777  14.6    %          99
778  11.4    %          99
779   4.3    %          99

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mospi.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(